### ISSUE TITLE
Maven plugin problem with Hosebird

### ISSUE THREAD

**Issue by nwaltner** [twitter/hbc#150]
Hi,

I'm new to Maven, so I'm sure that I'm doing something stupid.

1. I am running this command in shell in the hbc-master sub-directory.
"mvn install && mvn exec:java -X -pl hbc-example -Dconsumer.key=$access_token -Dconsumeor.secret=$access_token_secret -Daccess.token=$consumer_key -Daccess.token.secret=$consumer_secret"

2. I can run "mvn install" works fine just.

3. But, when I try to execute with my passwords I get a warning (see below) and then a failure with
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java

4. I must not have the plug-in in the correct spot, no?

5. I have googled this endlessly, but my knowledge of Java is too shallow to figure this out.

Any ideas?

Regards,

Nick
206.972.1456

[DEBUG] joining on thread Thread[com.twitter.hbc.example.SampleStreamExample.main(),5,com.twitter.hbc.example.SampleStreamExample]
[DEBUG] Setting accessibility to true in order to invoke main().
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
	at com.twitter.hbc.httpclient.auth.OAuth1.<init>(OAuth1.java:52)
	at com.twitter.hbc.example.SampleStreamExample.run(SampleStreamExample.java:39)
	at com.twitter.hbc.example.SampleStreamExample.main(SampleStreamExample.java:77)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.633 s
[INFO] Finished at: 2015-06-11T18:26:22-07:00
[INFO] Final Memory: 9M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project hbc-example: An exception occured while executing the Java class. null: InvocationTargetException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project hbc-example: An exception occured while executing the Java class. null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. null
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:352)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
	at com.twitter.hbc.httpclient.auth.OAuth1.<init>(OAuth1.java:52)
	at com.twitter.hbc.example.SampleStreamExample.run(SampleStreamExample.java:39)
	at com.twitter.hbc.example.SampleStreamExample.main(SampleStreamExample.java:77)
	... 6 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
arussos-iMac:hbc-master arusso$

**Comment by kevinoliver** [comment]
If you look at the stacktrace its triggered here:

```
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
at com.twitter.hbc.httpclient.auth.OAuth1.(OAuth1.java:52)
at com.twitter.hbc.example.SampleStreamExample.run(SampleStreamExample.java:39)
at com.twitter.hbc.example.SampleStreamExample.main(SampleStreamExample.java:77)
... 6 more
```


Make sure you are giving it a consumerKey: https://github.com/twitter/hbc/blob/master/hbc-core/src/main/java/com/twitter/hbc/httpclient/auth/OAuth1.java#L52

**Comment by nwaltner** [comment]
Thanks. My shell was foobared. GIGO as they say. Thx again.

**Comment by nwaltner** [comment]
Kevin,

Thanks. It turned out that I foobared my shell script. My bad.
I’m twittering away now.

Regards,

Nick

On Jun 12, 2015, at 9:19 AM, Kevin Oliver <notifications@github.com> wrote:

> If you look at the stacktrace its triggered here:
> 
> Caused by: java.lang.NullPointerException
> at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
> at com.twitter.hbc.httpclient.auth.OAuth1.(OAuth1.java:52)
> at com.twitter.hbc.example.SampleStreamExample.run(SampleStreamExample.java:39)
> at com.twitter.hbc.example.SampleStreamExample.main(SampleStreamExample.java:77)
> ... 6 more
> Make sure you are giving it a consumerKey: https://github.com/twitter/hbc/blob/master/hbc-core/src/main/java/com/twitter/hbc/httpclient/auth/OAuth1.java#L52
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Waltner
Managing Principal

Phone:      (206) 254-0223
Cellular:   (206) 972-1456

1201 3rd Avenue
Suite 5030
Seattle, WA 98101
