### ISSUE TITLE
Exception when parsing FOLLOWS_OVER_LIMIT warnings

### ISSUE THREAD

**Issue by rowanseymour** [twitter/hbc#155]
This type of warning doesn't have the "percent_full" field, thus the following error:

```
WARN com.twitter.hbc.twitter4j.BaseTwitter4jClient: Exception thrown during parsing msg {"warning":{"code":"FOLLOWS_OVER_LIMIT","message":"The requested user follows more accounts than the maximum supported by this streaming endpoint. Only a subset of 10000 followed accounts are included in this stream.","user_id":????????,"timestamp_ms":"1439407322431"}}

! twitter4j.JSONException: JSONObject["percent_full"] not found.
! at twitter4j.JSONObject.get(JSONObject.java:390)
! at twitter4j.JSONObject.getInt(JSONObject.java:428)
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient.processStallWarning(BaseTwitter4jClient.java:255)
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient.processMessage(BaseTwitter4jClient.java:215)
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient.parseMessage(BaseTwitter4jClient.java:129)
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient$1.run(BaseTwitter4jClient.java:76) 
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:745)
```

**Comment by rowanseymour** [comment]
Is this project still being maintained? I can make a PR if someone will merge it.

**Comment by andypiper** [comment]
Hi @rowanseymour feel free to fork, fix and submit a PR and I'll do my best to review, however we are not spending a lot of time actively working on this code base at the moment. You're free to fix and work on this yourself too, of course. Apologies for the delay in finding you a response on this.

**Comment by rowanseymour** [comment]
Hi @andypiper I know it's been a while but I finally got some time to spend on this and made https://github.com/twitter/hbc/pull/176 to fix this bug. If you can find time to review and merge that would be much appreciated.
